# Generated by Django 5.0.4 on 2025-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0068_roomtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
