# Generated by Django 5.0.4 on 2025-04-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0069_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='Hostel_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_No',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_Type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
