# Generated by Django 5.0.4 on 2025-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0071_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
