# Generated by Django 5.0.4 on 2025-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0072_student_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
