# Generated by Django 5.0.4 on 2025-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0073_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Eight_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Five_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Four_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Nine_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='One_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Seven_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Six_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Ten_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Three_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='Two_Seater_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
