# Generated by Django 5.0.4 on 2025-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0074_hostel_eight_seater_price_hostel_five_seater_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
