# Generated by Django 5.0.4 on 2025-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0075_student_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='payment_type',
            field=models.CharField(choices=[('HOSTEL', 'Hostel Payment'), ('MESS', 'Mess Payment')], default='MESS', max_length=10),
        ),
    ]
