# Generated by Django 5.0.4 on 2025-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0076_stripepayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount_Due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
