# Generated by Django 5.0.4 on 2025-04-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0077_payment_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Amount_Due',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='payment_type',
        ),
    ]
