# Generated by Django 5.0.4 on 2025-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0078_remove_payment_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount_Due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
