# Generated by Django 5.0.4 on 2025-04-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0079_payment_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('BANK', 'Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Voucher_No',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
