# Generated by Django 5.0.4 on 2025-04-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0081_student_paid_installments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid_installments_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='partially_paid_installments_count',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Amount_Paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Fee_Status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PENDING', 'Pending')], default='UNPAID', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('BANK', 'Bank')], max_length=50, null=True),
        ),
    ]
