# Generated by Django 5.0.4 on 2025-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0082_remove_student_paid_installments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_installment_count',
            field=models.IntegerField(default=0),
        ),
    ]
