# Generated by Django 5.0.4 on 2025-04-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0083_student_paid_installment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepayment',
            name='stripe_charge_id',
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_record', to='hostel.payment'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='semester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
