# Generated by Django 5.0.4 on 2025-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0084_remove_stripepayment_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messbill',
            options={'ordering': ['bill_date']},
        ),
        migrations.RemoveField(
            model_name='messbill',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='messbill',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='messbill',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='messpaymentrequest',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='messpaymentrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='messpaymentrequest',
            name='processed_date',
        ),
        migrations.AddField(
            model_name='messbill',
            name='bill_month',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messbill',
            name='bill_year',
            field=models.IntegerField(default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messpayment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messpaymentrequest',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='messpaymentrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ADMIN', 'Admin Approved'), ('STRIPE', 'Stripe'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='milestone_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='request_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.DeleteModel(
            name='FaceDetectionRecord',
        ),
    ]
