# Generated by Django 5.0.4 on 2025-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0086_alter_stripepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='semester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
