# Generated by Django 5.0.4 on 2025-05-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0088_alter_stripepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='semester',
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_type',
            field=models.CharField(choices=[('HOSTEL', 'Hostel Fee'), ('MESS', 'Mess Fee')], default='MESS', max_length=10),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to='hostel.payment'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student'),
        ),
    ]
