# Generated by Django 5.0.4 on 2025-05-01 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0090_stripepayment_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='stripe_session_id',
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_record', to='hostel.payment'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to='hostel.student'),
        ),
    ]
