# Generated by Django 5.0.4 on 2025-05-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0092_alter_stripepayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={},
        ),
    ]
