# Generated by Django 5.0.4 on 2025-05-02 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0093_alter_stripepayment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messpaymentrequest',
            old_name='request_note',
            new_name='admin_note',
        ),
        migrations.RenameField(
            model_name='messpaymentrequest',
            old_name='stripe_payment_intent_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='messpaymentrequest',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payment_screenshots/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='messpaymentrequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='bills',
            field=models.ManyToManyField(blank=True, to='hostel.messbill'),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='milestone_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='messpaymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
