# Generated by Django 5.0.4 on 2025-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0095_messfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
